version: '2'

services:
  symfony:
    build: ./
    volumes:
      - ./:/var/www:rw
      - ./app/logs/symfony:/var/www/app/logs/symfony:rw
      - ./app/logs/nginx:/var/www/app/logs/nginx:rw

  nginx:
    build: ./Docker/nginx/
    ports:
      - 8080:80 # You can customize this if you want
    links:
      - fpm
    volumes_from:
      - symfony
    environment:
      <APP_SERVER_NAME>: yourAppName
    networks:
      default:
        ipv4_address: 192.168.21.102 #You can change this if you want. Just make sure everyhting else in your code that depends on this is changed accordingly
        # Also, it's the main ip address you can hit to access your app.
        # If you happen to change it, make sure to change the networks subnet accordingly
  fpm:
    build: ./Docker/php-fpm/
    links:
      - mysql
    volumes_from:
      - symfony
    environment:
      APP_SERVER_NAME: yourAppName
    networks:
      default:
        ipv4_address: 192.168.21.103

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
    - 3306:3306 # Customize this if you want
    volumes:
    - ./Docker/.data/db:/var/lib/mysql:rw
    environment:
    - "MYSQL_ROOT_PASSWORD=rootPW"
    - "MYSQL_USER=user"
    - "MYSQL_PASSWORD=password"
    - "MYSQL_DATABASE=databaseName"
    networks:
      default:
        ipv4_address: 192.168.21.104

networks:
  default:
    ipam:
      config:
      - subnet: 192.168.21.0/24 # This is the subnet you must change if you want to customize the ip addresses
