version: '2'

services:
  symfony:
    build: ./
    volumes:
      - ./:/var/www:rw
      - ./app/logs/symfony:/var/www/app/logs/symfony:rw
      - ./app/logs/nginx:/var/www/app/logs/nginx:rw

  nginx:
    build: ./Docker/nginx/
    ports:
      - 8080:80
    links:
      - fpm
    volumes_from:
      - symfony
    environment:
      <APP_SERVER_NAME>: baskofon
    networks:
      default:
        ipv4_address: 192.168.21.102

  fpm:
    build: ./Docker/php-fpm/
    links:
      - mysql
    volumes_from:
      - symfony
    environment:
      APP_SERVER_NAME: baskofon
    networks:
      default:
        ipv4_address: 192.168.21.103

  mysql:
    image: mysql
    ports:
    - 3306:3306
    volumes:
    - ./Docker/.data/db:/var/lib/mysql:rw
    environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_USER=root"
    - "MYSQL_PASSWORD=root"
    - "MYSQL_DATABASE=baskofon"
    networks:
      default:
        ipv4_address: 192.168.21.104

networks:
  default:
    ipam:
      config:
      - subnet: 192.168.21.0/24